# Generated by Django 3.2.13 on 2022-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220512_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='FirstName',
            field=models.CharField(default='User', max_length=25, verbose_name='FirstName'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='LastName',
            field=models.CharField(default='Name', max_length=25, verbose_name='LastName'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='resetpassword',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
    ]
