# Generated by Django 4.0.2 on 2022-05-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_portfoliomodel_portfoliopub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='portfolioPub',
            field=models.CharField(choices=[('1', 'Ẩn'), ('2', 'Hiện')], default='1', max_length=250),
        ),
    ]
