# Generated by Django 3.2.13 on 2022-05-11 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_portfoliomodel_portfoliopub'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioDatePub',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='portfolioTimePub',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
