# Generated by Django 3.2.13 on 2022-05-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_alter_productsmodel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='inventory',
            field=models.FloatField(default=0, verbose_name='Hàng tồn kho'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='productsPrice',
            field=models.FloatField(default=0, verbose_name='Giá bán'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='productsPriceOther',
            field=models.FloatField(default=0, verbose_name='Giá so sánh'),
        ),
    ]
