# Generated by Django 4.0.4 on 2022-05-24 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_ordermodel_odertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='oderTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian mua'),
        ),
    ]
