# Generated by Django 4.0.2 on 2022-05-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioPub',
            field=models.CharField(default=213, max_length=250),
            preserve_default=False,
        ),
    ]
