# Generated by Django 3.2.13 on 2022-05-11 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_auto_20220511_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='portfolioDatePub',
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='portfolioTimePub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
