# Generated by Django 3.2.13 on 2022-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_auto_20220511_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='portfolioTimePub',
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='portfolioPub',
            field=models.CharField(choices=[('1', 'Hiển Thị'), ('2', 'Ẩn')], default='1', max_length=250, verbose_name='Hiển thị'),
        ),
    ]
