# Generated by Django 3.2.13 on 2022-05-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_auto_20220512_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsName', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('productsBody', models.TextField(verbose_name='Mô tả sản phẩm')),
                ('productsImg', models.FileField(upload_to='', verbose_name='Ảnh sản phẩm')),
                ('productsPrice', models.IntegerField(verbose_name='Giá bán')),
                ('productsPriceOther', models.IntegerField(verbose_name='Giá so sánh')),
                ('productsPub', models.CharField(choices=[('1', 'Hiển Thị'), ('2', 'Ẩn')], default='1', max_length=250, verbose_name='Hiển thị')),
                ('productsTimePub', models.DateTimeField(verbose_name='Thời gian hiển thị')),
                ('weight', models.FloatField(verbose_name='Khối luộng sản phẩm')),
                ('portfolioModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.portfoliomodel')),
            ],
        ),
    ]
