# Generated by Django 3.2.13 on 2022-05-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_auto_20220511_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='portfolioBody',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='portfolioImg',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='portfolioPub',
        ),
    ]
