# Generated by Django 3.2.13 on 2022-05-11 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_productsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='Hàng tồn kho'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='portfolioTimePub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian hiển thị'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='productsPrice',
            field=models.IntegerField(default=0, verbose_name='Giá bán'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='productsPriceOther',
            field=models.IntegerField(default=0, verbose_name='Giá so sánh'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='productsTimePub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian hiển thị'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Khối luộng sản phẩm'),
        ),
    ]
