# Generated by Django 3.2.13 on 2022-05-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_auto_20220511_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioBody',
            field=models.TextField(default=1, verbose_name='Mô tả danh sách'),
            preserve_default=False,
        ),
    ]
