# Generated by Django 3.2.13 on 2022-05-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_portfoliomodel_portfoliobody'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioPub',
            field=models.CharField(choices=[('1', 'Hiển Thị'), ('2', 'Ẩn')], default='1', max_length=250, verbose_name='Hiển thị'),
        ),
    ]
