# Generated by Django 3.2.13 on 2022-05-11 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_portfoliomodel_portfoliopub'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioTimePub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian hiển thị'),
        ),
    ]
