# Generated by Django 3.2.13 on 2022-05-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_auto_20220512_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='portfolioModel',
        ),
    ]
