# Generated by Django 3.2.13 on 2022-05-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_portfoliomodel_portfoliotimepub'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioImg',
            field=models.FileField(default=1, upload_to='', verbose_name='Ảnh minh họa'),
            preserve_default=False,
        ),
    ]
