# Generated by Django 3.2.13 on 2022-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_productsmodel_portfoliomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Khối lượng sản phẩm'),
        ),
    ]
