# Generated by Django 3.2.13 on 2022-05-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_auto_20220512_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='portfolioModel',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='productsPub',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='productsTimePub',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='weight',
        ),
    ]
