# Generated by Django 3.2.13 on 2022-05-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_remove_portfoliomodel_portfolioimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='portfolioTimePub',
            field=models.DateTimeField(verbose_name='Thời gian hiển thị'),
        ),
    ]
