# Generated by Django 4.0.4 on 2022-05-18 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_auto_20220513_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='productsTimePub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian hiển thị'),
        ),
    ]
