# Generated by Django 4.0.4 on 2022-05-18 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_auto_20220513_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='productsDatePub',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày hiển thị'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='productsTimePub',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Giờ hiển thị'),
        ),
    ]
