# Generated by Django 3.2.13 on 2022-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_alter_portfoliomodel_portfoliotimepub'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioImg',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
