# Generated by Django 3.2.13 on 2022-05-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_auto_20220512_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='Hàng tồn kho'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='productsPub',
            field=models.CharField(choices=[('1', 'Hiển Thị'), ('2', 'Ẩn')], default='1', max_length=250, verbose_name='Hiển thị'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='productsTimePub',
            field=models.DateTimeField(default=2, verbose_name='Thời gian hiển thị'),
            preserve_default=False,
        ),
    ]
