# Generated by Django 4.0.4 on 2022-05-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0017_alter_productsmodel_productstimepub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='productsPub',
        ),
    ]
