# Generated by Django 4.0.4 on 2022-05-18 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0018_remove_productsmodel_productspub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='portfolioPub',
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='portfolioTimePub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian hiển thị'),
        ),
    ]
