# Generated by Django 3.2.13 on 2022-05-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0019_remove_portfoliomodel_portfoliopub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='Hàng tồn kho'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='productsPrice',
            field=models.IntegerField(default=0, verbose_name='Giá bán'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='productsPriceOther',
            field=models.IntegerField(default=0, verbose_name='Giá so sánh'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Khối lượng sản phẩm'),
        ),
    ]
