# Generated by Django 3.2.13 on 2022-05-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0019_portfoliomodel_portfolioimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='portfolioImg',
            field=models.FileField(upload_to=''),
        ),
    ]
