# Generated by Django 3.2.13 on 2022-05-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0020_alter_portfoliomodel_portfolioimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='portfolioImg',
        ),
    ]
