# Generated by Django 3.2.13 on 2022-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0021_remove_portfoliomodel_portfolioimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioImg',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
