# Generated by Django 3.2.13 on 2022-05-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0023_auto_20220511_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioBody',
            field=models.TextField(default=1, verbose_name='Mô tả danh sách'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioName',
            field=models.CharField(default=1, max_length=200, verbose_name='Tên danh sách'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioPub',
            field=models.CharField(choices=[('1', 'Hiển Thị'), ('2', 'Ẩn')], default='1', max_length=250, verbose_name='Hiển thị'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolioTimePub',
            field=models.DateTimeField(default=1, verbose_name='Thời gian hiển thị'),
            preserve_default=False,
        ),
    ]
