# Generated by Django 3.2.13 on 2022-05-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0025_auto_20220511_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='portfolioBody',
        ),
    ]
