# Generated by Django 4.0.2 on 2022-04-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacform',
            old_name='usename',
            new_name='username',
        ),
    ]
