# Generated by Django 4.0.2 on 2022-04-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_usename_contacform_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacForm',
            new_name='contactModel',
        ),
    ]
