# Generated by Django 4.0.2 on 2022-04-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_contacform_contactmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactModel',
            new_name='contactForm',
        ),
    ]
