# Generated by Django 4.0.2 on 2022-04-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_contactmodel_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactForm',
            new_name='contactModel',
        ),
    ]
