# Generated by Django 4.0.2 on 2022-05-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_possform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='possForm',
            new_name='postBlog',
        ),
    ]
