# Generated by Django 3.2.13 on 2022-05-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20220513_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='', max_length=30, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='resetpassword',
            field=models.CharField(default='', max_length=30, verbose_name='resetpassword'),
        ),
    ]
