# Generated by Django 3.2.13 on 2022-05-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userName',
            field=models.CharField(default='', max_length=25, verbose_name='UserName'),
        ),
    ]
