# Generated by Django 4.0.4 on 2022-05-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='pay',
            field=models.CharField(default=1, max_length=255, verbose_name='Phương Thức Thanh Toán'),
            preserve_default=False,
        ),
    ]
