# Generated by Django 3.2.13 on 2022-05-23 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_cartitemhistorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItemHistoryModel',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.carthistorymodel'),
        ),
    ]
