# Generated by Django 3.2.13 on 2022-05-23 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20220524_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='cart',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='listProducts',
            field=models.CharField(default='', max_length=10000, verbose_name='ID cac san pham da mua'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='listQuantile',
            field=models.CharField(default='', max_length=10000, verbose_name='So luong cac san pham da mua'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.usermodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CartHistoryModel',
        ),
    ]
