# Generated by Django 3.2.13 on 2022-05-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20220524_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='tongTien',
            field=models.IntegerField(default=0, verbose_name='Tong tien hoa don'),
        ),
    ]
