# Generated by Django 3.2.13 on 2022-05-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_ordermodel_tongtien'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='OrderModel1',
        ),
    ]
