# Generated by Django 4.0.4 on 2022-05-24 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_ordermodel_ordermodel1'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShipAddress', models.CharField(max_length=255, verbose_name='Địa chỉ ship')),
                ('order_description', models.TextField(default='')),
                ('pay', models.CharField(max_length=255, verbose_name='Phương Thức Thanh Toán')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cartmodel')),
            ],
        ),
    ]
