# Generated by Django 4.0.4 on 2022-05-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
